CREATE TABLE students (
  studentId VARCHAR(50) PRIMARY KEY,
  keyNumber VARCHAR(50) UNIQUE,
  used BOOLEAN DEFAULT 0
);

CREATE TABLE candidates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) UNIQUE
);

CREATE TABLE votes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentId VARCHAR(50),
  candidate VARCHAR(100),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(100),
  studentId VARCHAR(50),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);